[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#### SCORING LOOP CHANGES ####
# Until the next section, all following patches affect function G.FUNCS.evaluate_play

# When playing an ascended hand, increase G.GAME.cry_asc_played
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
G.GAME.hands[text].played_this_round = G.GAME.hands[text].played_this_round + 1
'''
position = "before"
payload = '''
if (G.GAME.current_round.current_hand.cry_asc_num or -2) > (G.GAME.cry_exploit_override and 1 or 0) then
    G.GAME.cry_asc_played = G.GAME.cry_asc_played and G.GAME.cry_asc_played+1 or 1
end
'''
match_indent = true

# Scoring loop ascends mult and chips
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
'''
position = "at"
payload = '''
delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = Spectrallib.ascend(G.GAME.hands[text].mult), chips = Spectrallib.ascend(G.GAME.hands[text].chips)})
'''
match_indent = true

# (TARGETS MULTIPLE)
# Mult is ascended
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
mult = mod_mult(G.GAME.hands[text].mult)
'''
position = "at"
payload = '''
mult = mod_mult(Spectrallib.ascend(G.GAME.hands[text].mult))
'''
match_indent = true

# (TARGETS MULTIPLE)
# Chips are ascended
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
hand_chips = mod_chips(G.GAME.hands[text].chips)
'''
position = "at"
payload = '''
hand_chips = mod_chips(Spectrallib.ascend(G.GAME.hands[text].chips))
'''
match_indent = true

# After scoring loop ends, clear ascension power text for now
# apparently - (this is slightly invasive, should switch to regex)
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
check_and_set_high_score('hand', SMODS.calculate_round_score())
'''
position = "before"
payload = '''
G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
        G.GAME.current_round.current_hand.cry_asc_num = 0
        G.GAME.current_round.current_hand.cry_asc_num_text = ''
        return true
    end
}))
'''
match_indent = true

# After scoring loop ends, clear ascension power for now
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
-- context.final_scoring_step calculations
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, final_scoring_step = true})
'''
position = 'before'
payload = '''
G.E_MANAGER:add_event(Event{
    trigger = "after",
    blocking = false,
    func = function()
        G.GAME.asc_power_hand = nil
        return true
    end
})
'''
match_indent = true

#### MISCELLANEOUS ####

# In Steamodded:
# function SMODS.upgrade_poker_hands
# Display ascended values when upgrading hands (I think like during Space Joker)
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
update_hand_text({delay = 0}, {[parameter] = G.GAME.hands[hand][parameter], StatusText = StatusText})
'''
position = "at"
payload = '''
if parameter == "chips" or parameter == "mult" then
    update_hand_text({delay = 0}, {[parameter] = Spectrallib.ascend(G.GAME.hands[hand][parameter]), StatusText = StatusText})
else
    update_hand_text({delay = 0}, {[parameter] = G.GAME.hands[hand][parameter], StatusText = StatusText})
end
'''
match_indent = true

# function CardArea:parse_highlighted
# Ascend mult and chips when cards are selected
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''
update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
'''
position = "at"
payload = '''
update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = Spectrallib.ascend(G.GAME.hands[text].mult), chips = Spectrallib.ascend(G.GAME.hands[text].chips)})
'''
match_indent = true

# In Steamodded:
# function create_UIBox_current_hands
# Add ascension power information to poker hand menu
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''
local t = {
    n = G.UIT.O,
'''
position = 'before'
payload = '''
if not in_collection and ((G.GAME.cry_asc_played or 0) > 0) then
    table.insert(object.nodes[1].nodes, Spectrallib.create_UIBox_asc_hands())
end
'''
match_indent = true