[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

#### BLIND CUSTOMIZATION ####

# function G.FUNCS.discard_cards_from_highlighted
# Implement Spectrallib.return_to_deck()
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "draw_card(G.hand, G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])"
position = "at"
payload = '''draw_card(G.hand, Spectrallib.return_to_deck() and G.deck or G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])'''
match_indent = true

# function ease_background_colour_blind
# Implement Spectrallib.get_bg_colour() for Small and Big Blinds
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
ease_background_colour{new_colour = G.C.BLIND['Small'], contrast = 1}
'''
position = "at"
payload = '''
ease_background_colour{new_colour = Spectrallib.get_bg_colour(), contrast = 1}
'''
match_indent = true

# function create_UIBox_blind_popup
# Spectrallib.get_blind_size_text sets the text for the blind's size
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "{n=G.UIT.T, config={text = blind.mult..localize('k_x_base'), scale = 0.4, colour = G.C.RED}},"
position = "at"
payload = "Spectrallib.get_blind_size_text(blind),"
match_indent = true

#### Spectrallib.get_blind_font ####

# function Game:update
# Spectrallib.get_blind_font affects debuff text
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'at'
pattern = '''
{n=G.UIT.R, config = {align = 'cm', maxw = 1}, nodes={
    {n=G.UIT.O, config={func = "update_blind_debuff_text", object = DynaText({scale = 0.6, string = SMODS.debuff_text or G.GAME.blind:get_loc_debuff_text(), maxw = 9, colours = {G.C.WHITE},float = true, shadow = true, silent = true, pop_in = 0, pop_in_rate = 6})}},
}}
'''
payload = '''
{n=G.UIT.R, config = {align = 'cm', maxw = 1}, nodes={
    {n=G.UIT.O, config={func = "update_blind_debuff_text", object = DynaText({scale = 0.6, font = Spectrallib.get_blind_font(G.GAME.blind), string = SMODS.debuff_text or G.GAME.blind:get_loc_debuff_text(), maxw = 9, colours = {G.C.WHITE},float = true, shadow = true, silent = true, pop_in = 0, pop_in_rate = 6})}},
}}
'''
match_indent = true

# function create_UIBox_blind_popup
# Spectrallib.get_blind_font affects popup text
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
position = 'at'
pattern = '''
ability_text[#ability_text + 1] = {n=G.UIT.R, config={align = "cm"}, nodes=SMODS.localize_box(v, {default_col = target.text_colour or G.C.WHITE, shadow = true, vars = target.vars, scale = target.scale})}
'''
payload = '''
ability_text[#ability_text + 1] = {n=G.UIT.R, config={align = "cm"}, nodes=SMODS.localize_box(v, {default_col = target.text_colour or G.C.WHITE, shadow = true, vars = target.vars, scale = target.scale, font = Spectrallib.get_blind_font(blind)})}
'''
match_indent = true

# function create_UI_blind_choice
# Spectrallib.get_blind_font affects blind description on the selection menu
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
position = 'at'
pattern = '''
blind_desc_nodes[#blind_desc_nodes+1] = {n=G.UIT.R, config={align = "cm", maxw = 2.8}, nodes=SMODS.localize_box(v, {default_col = disabled and G.C.UI.TEXT_INACTIVE or target.text_colour or G.C.WHITE, shadow = not disabled, vars = target.vars, scale = target.scale})}
'''
payload = '''
blind_desc_nodes[#blind_desc_nodes+1] = {n=G.UIT.R, config={align = "cm", maxw = 2.8}, nodes=SMODS.localize_box(v, {default_col = disabled and G.C.UI.TEXT_INACTIVE or target.text_colour or G.C.WHITE, shadow = not disabled, vars = target.vars, scale = target.scale, font = Spectrallib.get_blind_font(blind_choice)})}
'''
match_indent = true

# function create_UIBox_HUD_blind
# Spectrallib.get_blind_font affects blind description on the side bar
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
position = 'at'
pattern = '''
{n=G.UIT.R, config={align = "cm", id = 'HUD_blind_debuff', func = 'HUD_blind_debuff'}, nodes={}},
'''
payload = '''
{n=G.UIT.R, config={align = "cm", id = 'HUD_blind_debuff', func = 'HUD_blind_debuff', font = Spectrallib.get_blind_font(G.GAME.blind)}, nodes={}},
'''
match_indent = true

# In Steamodded:
# function G.FUNCS.HUD_blind_debuff
# Spectrallib.get_blind_font affects whatever idfk
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
position = 'at'
pattern = '''
local node_def 
if type(G.GAME.blind.loc_debuff_lines[i]) == "string" then
    node_def = {n = G.UIT.R, config = {align = "cm", minh = 0.3, maxw = 4.2}, nodes = {
    {n = G.UIT.T, config = {ref_table = G.GAME.blind.loc_debuff_lines, ref_value = i, scale = scale * 0.9, colour = G.C.UI.TEXT_LIGHT}}}}
else
    node_def = {n = G.UIT.R, config = {align = "cm", minh = 0.3, maxw = 4.2}, nodes = SMODS.localize_box(G.GAME.blind.loc_debuff_lines[i], {default_col = G.GAME.blind.loc_debuff_lines.text_colour or G.C.UI.TEXT_LIGHT, scale = 1.125 * (G.GAME.blind.loc_debuff_lines.scale or 1), vars = G.GAME.blind.loc_debuff_lines.vars or {}})}
end
'''
payload = '''
local node_def 
if type(G.GAME.blind.loc_debuff_lines[i]) == "string" then
    node_def = {n = G.UIT.R, config = {align = "cm", minh = 0.3, maxw = 4.2}, nodes = {
    {n = G.UIT.T, config = {ref_table = G.GAME.blind.loc_debuff_lines, ref_value = i, font = Spectrallib.get_blind_font(G.GAME.blind), scale = scale * 0.9, colour = G.C.UI.TEXT_LIGHT}}}}
else
    node_def = {n = G.UIT.R, config = {align = "cm", minh = 0.3, maxw = 4.2}, nodes = SMODS.localize_box(G.GAME.blind.loc_debuff_lines[i], {default_col = G.GAME.blind.loc_debuff_lines.text_colour or G.C.UI.TEXT_LIGHT, scale = 1.125 * (G.GAME.blind.loc_debuff_lines.scale or 1), vars = G.GAME.blind.loc_debuff_lines.vars or {}, font = Spectrallib.get_blind_font(G.GAME.blind)})}
end
'''
match_indent = true

#### Spectrallib.get_blind_amount ####

# function create_UIBox_blind_choice
# Using Spectrallib.get_blind_amount
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling"
position = "at"
payload = "local blind_amt = Spectrallib.get_blind_amount(blind_choice.config, nil, get_blind_amount(G.GAME.round_resets.blind_ante))*G.GAME.starting_params.ante_scaling"
match_indent = true

# function Blind:set_blind
# Using Spectrallib.get_blind_amount
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling"
position = "at"
payload = "self.chips = Spectrallib.get_blind_amount(self.config.blind, self, get_blind_amount(G.GAME.round_resets.ante))*G.GAME.starting_params.ante_scaling"
match_indent = true

#### FRACTIONAL/NEGATIVE ANTES ####

# function get_new_boss
# Showdown boss only appears once per integer component
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif v.boss.showdown and (G.GAME.round_resets.ante)%G.GAME.win_ante == 0 and G.GAME.round_resets.ante >= 2 then
    eligible_bosses[k] = res and true or nil
'''
position = "after"
payload = '''
else
    local ante_modu = (G.GAME.round_resets.ante)%G.GAME.win_ante
    local ante_int = math.floor(G.GAME.round_resets.ante or 1)
    local last_boss_ante_int = math.floor(G.GAME.last_boss_ante or 1)
    if (
        v.boss.showdown
        and 2 < G.GAME.round_resets.ante
        and (0 <= ante_modu and ante_modu < 1)
        and ante_int ~= last_boss_ante_int -- Fight showdown once per ante integer
    ) then
        eligible_bosses[k] = res and true or nil
    end
'''
match_indent = true