[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "draw_card(G.hand, G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i]) "
position = "at"
payload = '''draw_card(G.hand, Spectrallib.return_to_deck() and G.deck or G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "draw_card(G.hand, G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i]) "
position = "at"
payload = '''draw_card(G.hand, Spectrallib.return_to_deck() and G.deck or G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
ease_background_colour{new_colour = G.C.BLIND['Small'], contrast = 1}
'''
position = "at"
payload = '''
ease_background_colour{new_colour = Spectrallib.get_bg_colour(), contrast = 1}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif v.boss.showdown and (G.GAME.round_resets.ante)%G.GAME.win_ante == 0 and G.GAME.round_resets.ante >= 2 then
    eligible_bosses[k] = res and true or nil
'''
position = "after"
payload = '''
else
    local ante_modu = (G.GAME.round_resets.ante)%G.GAME.win_ante
    local ante_int = math.floor(G.GAME.round_resets.ante or 1)
    local last_boss_ante_int = math.floor(G.GAME.last_boss_ante or 1)
    if (
        v.boss.showdown
        and 2 < G.GAME.round_resets.ante
        and (0 <= ante_modu and ante_modu < 1)
        and ante_int ~= last_boss_ante_int -- Fight showdown once per ante integer
    ) then
        eligible_bosses[k] = res and true or nil
    end
'''
match_indent = true