[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

## self.ability.consumeable ##

# function Card:set_ability
# Remove CCD from enhanced cards
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if center.consumeable then 
	self.ability.consumeable = center.config
end  
'''
position = "before"
payload = '''
if not center.consumeable then
	self.ability.consumeable = nil
end
'''
match_indent = true

# function Card:can_use_consumeable
# nil check self.ability.consumeable
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if G.STATE == G.STATES.SELECTING_HAND or G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.PLANET_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED then
    if self.ability.consumeable.max_highlighted then
'''
position = "at"
payload = '''
if G.STATE == G.STATES.SELECTING_HAND or G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.PLANET_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED then
    if self.ability.consumeable and self.ability.consumeable.max_highlighted then
'''
match_indent = true

# function can_use_consumeable
# nil check self.ability.consumeable
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''end        if self.ability.name == 'The Hermit' or self.ability.consumeable.hand_type or self.ability.name == 'Temperance' or self.ability.name == 'Black Hole' then'''
position = "at"
payload = '''
end        if self.ability.name == 'The Hermit' or (self.ability.consumeable and self.ability.consumeable.hand_type) or self.ability.name == 'Temperance' or self.ability.name == 'Black Hole' then
'''
match_indent = true

## VANILLA FIXES ##

# function Card:can_use_consumeable (Aura)
# Prevent Aura from applying to itself if it's CCD
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if G.hand and (#G.hand.highlighted == 1) and G.hand.highlighted[1] and (not G.hand.highlighted[1].edition) then return true end"
position = "at"
payload = '''
if self.area ~= G.hand then
    return G.hand and (#G.hand.highlighted == 1) and G.hand.highlighted[1] and (not G.hand.highlighted[1].edition)
else
    local idx = 1
    if G.hand.highlighted[1] == self then
        local idx = 2
    end
    return (#G.hand.highlighted == 2) and (not G.hand.highlighted[idx].edition)
end
'''
match_indent = true

# function Card:set_edition, function Card:remove_from_deck
# Removing/adding negative from a CCD consumable will not affect G.consumeables
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """if self.ability.consumeable then"""
position = "at"
payload = """if self.ability.consumeable and not self.playing_card then"""
match_indent = true

## UI ##

# function Card:generate_UIBox_ability_table
# Prepare playing card data for CCD card tooltips
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''return generate_card_ui(self.config.center, nil, loc_vars, card_type, badges, hide_desc, main_start, main_end, self)'''
position = "before"
payload = '''
if card_type ~= 'Default' and card_type ~= 'Enhanced' and self.playing_card and not (SMODS.Mods["Cryptid"] or {}).can_load then
	loc_vars = loc_vars or {}
	loc_vars.ccd = {
		playing_card = not not self.base.colour, value = self.base.value, suit = self.base.suit, colour = self.base.colour,
		nominal_chips = self.base.nominal > 0 and self.base.nominal or nil,
		bonus_chips = (self.ability.bonus + (self.ability.perma_bonus or 0)) > 0 and (self.ability.bonus + (self.ability.perma_bonus or 0)) or nil,
        suit_bonus = self:get_suit_bonus_table(),
        rank_bonus = self:get_rank_bonus_table(),
	}
end
'''
match_indent = true

# function generate_card_ui
# Use aforementioned playing card data and generate UI accordingly
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''local loc_vars = {}'''
position = "before"
payload = '''
if specific_vars and specific_vars.ccd and not (SMODS.Mods["Cryptid"] or {}).can_load then
	full_UI_table.ccd = {name = {}, main = {}}
	localize{type = 'other', key = 'playing_card', set = 'Other', nodes = full_UI_table.ccd.name, vars = {localize(specific_vars.ccd.value, 'ranks'), localize(specific_vars.ccd.suit, 'suits_plural'), colours = {specific_vars.ccd.colour}}}
	full_UI_table.ccd.name = full_UI_table.ccd.name[1]
	if specific_vars.ccd.nominal_chips then
		localize{type = 'other', key = 'card_chips', nodes = full_UI_table.ccd.main, vars = {specific_vars.ccd.nominal_chips}}
	end
	if specific_vars.ccd.bonus_chips then
		localize{type = 'other', key = 'card_extra_chips', nodes = full_UI_table.ccd.main, vars = {specific_vars.ccd.bonus_chips}}
	end
    if specific_vars.ccd.suit_bonus and next(specific_vars.ccd.suit_bonus) then
        for _, v in ipairs(specific_vars.ccd.suit_bonus) do
            localize{type = 'other', key = v.loc_key, nodes = full_UI_table.ccd.main, vars = {localize(v.key, 'suits_plural'), v.chips, v.mult, v.level, colours = {
                G.C.SUITS[v.key],
                to_big(v.level) < to_big(2) and G.C.BLACK or G.C.HAND_LEVELS[to_number(math.min(7, v.level))]
            }}}
        end
	end
end
'''
match_indent = true

# function G.UIDEF.card_h_popup
# Add title and description of the CCD center
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local ret_val = {n=G.UIT.ROOT, config = {align = 'cm', colour = G.C.CLEAR}, nodes={'''
position = "before"
payload = '''

local slib_ret_rows = {}
if not (SMODS.Mods["Cryptid"] or {}).can_load and AUT.ccd then
    slib_ret_rows[#slib_ret_rows+1] = name_from_rows(AUT.ccd.name, G.C.WHITE)
    slib_ret_rows[#slib_ret_rows+1] = desc_from_rows(AUT.ccd.main)
end
if obj and obj.set == "Back" and not next(AUT.name) then
    AUT.name = localize{type = 'name', set = "Back", key = obj.key, nodes = AUT.name}
end
slib_ret_rows[#slib_ret_rows+1] = name_from_rows(AUT.name, is_playing_card and G.C.WHITE or nil)
slib_ret_rows[#slib_ret_rows+1] = desc_from_rows(AUT.main)
if badges[1] then
    slib_ret_rows[#slib_ret_rows+1] = {n=G.UIT.R, config={align = "cm", padding = 0.03}, nodes=badges}
end

'''
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
name_from_rows(AUT.name, is_playing_card and G.C.WHITE or nil),
desc_from_rows(AUT.main),
badges[1] and {n=G.UIT.R, config={align = "cm", padding = 0.03}, nodes=badges} or nil,
'''
position = "at"
payload = '''
unpack(slib_ret_rows)

'''
match_indent = true