[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Stuff can go in this file if there isnt anywhere better for it (yet)

#Adds additional tooltip to banned cards in the collection
[[patches]]
[patches.pattern]
match_indent = true
pattern = "for _, v in ipairs(info_queue) do"
position = 'before'
target = 'functions/common_events.lua'
payload = '''
if card and card.config and G.GAME.slib_banished_keys[card.config.center_key] and card.area and card.area.config.collection then
    info_queue[#info_queue+1] = { set = "Other", key = "slib_banned_card", }
end
'''

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local badge_text = DynaText({string = mod_name or 'ERROR', colours = {mod.badge_text_colour or G.C.WHITE}, maxw = mod.no_marquee and max_text_width, float = true, shadow = true, offset_y = -0.05, silent = true, spacing = 1*scale_fac, scale = text_height or 0.297})
'''
position = 'at'
target = '=[SMODS _ "src/utils.lua"]'
payload = '''
local badge_text = obj and obj.slib_credits and Spectrallib.get_credits_style():create_badge_text(mod, obj, width, text_height) or 
    DynaText({string = mod_name or 'ERROR', colours = {mod.badge_text_colour or G.C.WHITE}, maxw = mod.no_marquee and max_text_width, float = true, shadow = true, offset_y = -0.05, silent = true, spacing = 1*scale_fac, scale = text_height or 0.297})
'''

# Use rank's default chips for sorting for value manip reasons
[[patches]]
[patches.pattern]
match_indent = true
target = "card.lua"
pattern = "return 10*self.base.nominal*rank_mult + self.base.suit_nominal*mult + (self.base.suit_nominal_original or 0)*0.0001*mult + 10*self.base.face_nominal*rank_mult + 0.000001*self.unique_val"
position = "at"
payload = 'return 10*(Spectrallib.safe_get(SMODS.Ranks, self.base.value, "nominal") or 0)*rank_mult + self.base.suit_nominal*mult + (self.base.suit_nominal_original or 0)*0.0001*mult + 10*self.base.face_nominal*rank_mult + 0.000001*self.unique_val'