[manifest]
version = "1.0.0"
dump_lua = true
priority = -1



[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "perma_h_dollars = self.ability and self.ability.perma_h_dollars or 0,"
position = "after"
payload = """
slib_perma_xlog_chips = self.ability and self.ability.slib_perma_xlog_chips or 0,
slib_perma_h_xlog_chips = self.ability and self.ability.slib_perma_h_xlog_chips or 0,
slib_perma_xlog_mult = self.ability and self.ability.slib_perma_xlog_mult or 0,
slib_perma_h_xlog_mult = self.ability and self.ability.slib_perma_h_xlog_mult or 0,
slib_perma_plus_asc = self.ability and self.ability.slib_perma_plus_asc or 0,
slib_perma_h_plus_asc = self.ability and self.ability.slib_perma_h_plus_asc or 0,
slib_perma_x_asc = self.ability and self.ability.slib_perma_x_asc or 0,
slib_perma_h_x_asc = self.ability and self.ability.slib_perma_h_x_asc or 0,
slib_perma_exp_asc = self.ability and self.ability.slib_perma_exp_asc or 0,
slib_perma_h_exp_asc = self.ability and self.ability.slib_perma_h_exp_asc or 0,
slib_perma_e_chips = self.ability and self.ability.slib_perma_e_chips or 0,
slib_perma_h_e_chips = self.ability and self.ability.slib_perma_h_e_chips or 0,
slib_perma_e_mult = self.ability and self.ability.slib_perma_e_mult or 0,
slib_perma_h_e_mult = self.ability and self.ability.slib_perma_h_e_mult or 0,
slib_bonus_effects = self.ability and self.ability.slib_bonus_effects or {}, --TODO: decide if this should persist through set_ability or not, needs special logic if not
"""
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = "new_ability.p_dollars = center.config.p_dollars or 0"
position = "after"
payload = """
new_ability.slib_perma_xlog_chips = center.config.slib_perma_xlog_chips or 0
new_ability.slib_perma_h_xlog_chips = center.config.slib_perma_h_xlog_chips or 0
new_ability.slib_perma_xlog_mult = center.config.slib_perma_xlog_mult or 0
new_ability.slib_perma_h_xlog_mult = center.config.slib_perma_h_xlog_mult or 0
new_ability.slib_perma_plus_asc = center.config.slib_perma_plus_asc or 0
new_ability.slib_perma_h_plus_asc = center.config.slib_perma_h_plus_asc or 0
new_ability.slib_perma_x_asc = center.config.slib_perma_x_asc or 0
new_ability.slib_perma_h_x_asc = center.config.slib_perma_h_x_asc or 0
new_ability.slib_perma_exp_asc = center.config.slib_perma_exp_asc or 0
new_ability.slib_perma_h_exp_asc = center.config.slib_perma_h_exp_asc or 0
new_ability.slib_perma_e_chips = center.config.slib_perma_e_chips or 0
new_ability.slib_perma_h_e_chips = center.config.slib_perma_h_e_chips or 0
new_ability.slib_perma_e_mult = center.config.slib_perma_e_mult or 0
new_ability.slib_perma_h_e_mult = center.config.slib_perma_h_e_mult or 0
new_ability.slib_bonus_effects = center.config.slib_bonus_effects or {} --TODO: decide if this should persist through set_ability or not, needs special logic if not
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "bonus_x_chips = self.ability.perma_x_chips ~= 0 and (self.ability.perma_x_chips + 1) or nil,"
position = "after"
payload = """
slib_perma_xlog_chips = self.ability.slib_perma_xlog_chips ~= 0 and self.ability.slib_perma_xlog_chips or nil,
slib_perma_h_xlog_chips = self.ability.slib_perma_h_xlog_chips ~= 0 and self.ability.slib_perma_h_xlog_chips or nil,
slib_perma_xlog_mult = self.ability.slib_perma_xlog_mult ~= 0 and self.ability.slib_perma_xlog_mult or nil,
slib_perma_h_xlog_mult = self.ability.slib_perma_h_xlog_mult ~= 0 and self.ability.slib_perma_h_xlog_mult or nil,
slib_perma_plus_asc = self.ability.slib_perma_plus_asc ~= 0 and self.ability.slib_perma_plus_asc or nil,
slib_perma_h_plus_asc = self.ability.slib_perma_h_plus_asc ~= 0 and self.ability.slib_perma_h_plus_asc or nil,
slib_perma_x_asc = self.ability.slib_perma_x_asc ~= 0 and (self.ability.slib_perma_x_asc + 1) or nil,
slib_perma_h_x_asc = self.ability.slib_perma_h_x_asc ~= 0 and (self.ability.slib_perma_h_x_asc + 1) or nil,
slib_perma_exp_asc = self.ability.slib_perma_exp_asc ~= 0 and (self.ability.slib_perma_exp_asc + 1) or nil,
slib_perma_h_exp_asc = self.ability.slib_perma_h_exp_asc ~= 0 and (self.ability.slib_perma_h_exp_asc + 1) or nil,
suit_bonus = self:get_suit_bonus_table(),
rank_bonus = self:get_rank_bonus_table(),
slib_perma_e_chips = self.ability.slib_perma_e_chips ~= 0 and (self.ability.slib_perma_e_chips + 1) or nil,
slib_perma_h_e_chips = self.ability.slib_perma_h_e_chips ~= 0 and (self.ability.slib_perma_h_e_chips + 1) or nil,
slib_perma_e_mult = self.ability.slib_perma_e_mult ~= 0 and (self.ability.slib_perma_e_mult + 1) or nil,
slib_perma_h_e_mult = self.ability.slib_perma_h_e_mult ~= 0 and (self.ability.slib_perma_h_e_mult + 1) or nil,
"""
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
if specific_vars and specific_vars.bonus_repetitions then
        localize{type = 'other', key = 'card_extra_repetitions', nodes = desc_nodes, vars = {specific_vars.bonus_repetitions, localize(specific_vars.bonus_repetitions > 1 and 'b_retrigger_plural' or 'b_retrigger_single')}}
    end
'''
position = "after"
payload = '''
if specific_vars and specific_vars.slib_perma_xlog_chips then
    localize{ type = "other", key = "slib_perma_xlog_chips", nodes = desc_nodes, vars = {(specific_vars.slib_perma_xlog_chips)}}
end
if specific_vars and specific_vars.slib_perma_h_xlog_chips then
    localize{ type = "other", key = "slib_perma_h_xlog_chips", nodes = desc_nodes, vars = {(specific_vars.slib_perma_h_xlog_chips)}}
end
if specific_vars and specific_vars.slib_perma_xlog_mult then
    localize{ type = "other", key = "slib_perma_xlog_mult", nodes = desc_nodes, vars = {(specific_vars.slib_perma_xlog_mult)}}
end
if specific_vars and specific_vars.slib_perma_h_xlog_mult then
    localize{ type = "other", key = "slib_perma_h_xlog_mult", nodes = desc_nodes, vars = {(specific_vars.slib_perma_h_xlog_mult)}}
end
if specific_vars and specific_vars.slib_perma_plus_asc then
    localize{ type = "other", key = "slib_perma_plus_asc", nodes = desc_nodes, vars = {SMODS.signed(specific_vars.slib_perma_plus_asc)}}
end
if specific_vars and specific_vars.slib_perma_h_plus_asc then
    localize{ type = "other", key = "slib_perma_h_plus_asc", nodes = desc_nodes, vars = {SMODS.signed(specific_vars.slib_perma_h_plus_asc)}}
end
if specific_vars and specific_vars.slib_perma_x_asc then
    localize{ type = "other", key = "slib_perma_x_asc", nodes = desc_nodes, vars = {specific_vars.slib_perma_x_asc}}
end
if specific_vars and specific_vars.slib_perma_h_x_asc then
    localize{ type = "other", key = "slib_perma_h_x_asc", nodes = desc_nodes, vars = {specific_vars.slib_perma_h_x_asc}}
end
if specific_vars and specific_vars.slib_perma_exp_asc then
    localize{ type = "other", key = "slib_perma_exp_asc", nodes = desc_nodes, vars = {specific_vars.slib_perma_exp_asc}}
end
if specific_vars and specific_vars.slib_perma_h_exp_asc then
    localize{ type = "other", key = "slib_perma_h_exp_asc", nodes = desc_nodes, vars = {specific_vars.slib_perma_h_exp_asc}}
end
if specific_vars and specific_vars.slib_perma_e_chips then
    localize{ type = "other", key = "slib_perma_e_chips", nodes = desc_nodes, vars = {specific_vars.slib_perma_e_chips}}
end
if specific_vars and specific_vars.slib_perma_h_e_chips then
    localize{ type = "other", key = "slib_perma_h_e_chips", nodes = desc_nodes, vars = {specific_vars.slib_perma_h_e_chips}}
end
if specific_vars and specific_vars.slib_perma_e_mult then
    localize{ type = "other", key = "slib_perma_e_mult", nodes = desc_nodes, vars = {specific_vars.slib_perma_e_mult}}
end
if specific_vars and specific_vars.slib_perma_h_e_mult then
    localize{ type = "other", key = "slib_perma_h_e_mult", nodes = desc_nodes, vars = {specific_vars.slib_perma_h_e_mult}}
end
if specific_vars and specific_vars.suit_bonus and next(specific_vars.suit_bonus) then
    for _, v in ipairs(specific_vars.suit_bonus) do
        localize{ type = 'other', key = v.loc_key, nodes = desc_nodes, vars = {localize(v.key, 'suits_plural'), v.chips, v.mult, v.level, colours = {
            G.C.SUITS[v.key],
            to_big(v.level) < to_big(2) and G.C.BLACK or G.C.HAND_LEVELS[to_number(math.min(7, v.level))]
        }}}
    end
end
if specific_vars and specific_vars.rank_bonus and next(specific_vars.rank_bonus) then
    for _, v in ipairs(specific_vars.rank_bonus) do
        localize{ type = 'other', key = v.loc_key, nodes = desc_nodes, vars = {localize(v.key, 'ranks'), v.chips, v.mult, v.level, colours = {
            G.C.UI.TEXT_DARK,
            to_big(v.level) < to_big(2) and G.C.BLACK or G.C.HAND_LEVELS[to_number(math.min(7, v.level))]
        }}}
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """        -- TARGET: main scoring on played cards"""
position = "before"
payload = '''
local xlog_chips = card:get_slib_xlog_chips()
if xlog_chips ~= 0 then
    ret.playing_card.xlog_chips = xlog_chips
end
local xlog_mult = card:get_slib_xlog_mult()
if xlog_mult ~= 0 then
    ret.playing_card.xlog_mult = xlog_mult
end
local entr_plus_asc = card:get_slib_plus_asc()
if entr_plus_asc ~= 0 then
    ret.playing_card.plus_asc = entr_plus_asc
end
local entr_asc = card:get_slib_x_asc()
if entr_asc ~= 1 and entr_asc > 0 then
    ret.playing_card.x_asc = entr_asc
end
local entr_exp_asc = card:get_slib_exp_asc()
if entr_exp_asc ~= 1 then
    ret.playing_card.exp_asc = entr_exp_asc
end
local echips = card:get_slib_e_chips()
if echips ~= 1 then
    ret.playing_card.echips = echips
end
local emult = card:get_slib_e_mult()
if emult ~= 1 then
    ret.playing_card.emult = emult
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """        -- TARGET: main scoring on held cards"""
position = "before"
payload = '''
local xlog_chips = card:get_slib_h_xlog_chips()
if xlog_chips ~= 0 then
    ret.playing_card.xlog_chips = xlog_chips
end
local xlog_mult = card:get_slib_h_xlog_mult()
if xlog_mult ~= 0 then
    ret.playing_card.xlog_mult = xlog_mult
end
local entr_plus_asc = card:get_slib_h_plus_asc()
if entr_plus_asc ~= 0 then
    ret.playing_card.plus_asc = entr_plus_asc
end
local entr_asc = card:get_slib_h_x_asc()
if entr_asc ~= 1 and entr_asc > 0 then
    ret.playing_card.x_asc = entr_asc
end
local entr_exp_asc = card:get_slib_h_exp_asc()
if entr_exp_asc ~= 1 then
    ret.playing_card.exp_asc = entr_exp_asc
end
local echips = card:get_slib_h_e_chips()
if echips ~= 1 then
    ret.playing_card.echips = echips
end
local emult = card:get_slib_h_e_mult()
if emult ~= 1 then
    ret.playing_card.emult = emult
end
'''
match_indent = true

# Multiuse localization
[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''if main_end then'''
position = "before"
payload = '''
if cfg and cfg.slib_infinite_use then
    local loc = {}
	localize{type = 'other', key = 'slib_infiniuse', nodes = loc, }
	desc_nodes[#desc_nodes+1] = loc[1]
elseif cfg and cfg.cry_multiuse and (not card or (card.bypass_discovery_center or card.config.center.discovered)) and card_type ~= "Locked" then --bit hacky but it works
	local loc = {}
	localize{type = 'other', key = 'slib_multiuse', nodes = loc, vars = {cfg.cry_multiuse, colours = { Spectrallib.get_text_colour(card, _c) } }}
	desc_nodes[#desc_nodes+1] = loc[1]
end
'''
match_indent = true

# Delete - multiuse 1
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
if obj.keep_on_use and type(obj.keep_on_use) == 'function' then
    nc = obj:keep_on_use(card)
end
'''
position = "after"
payload = '''
if not nc and card.ability.slib_infinite_use then
    nc = true
    G.slib_infiniuse = true
elseif not nc and card.ability.cry_multiuse and (card.ability.cry_multiuse > 1) then
	card.ability.cry_multiuse = card.ability.cry_multiuse - 1
	nc = true
	G.cry_muse = true
end
'''
match_indent = true

# Multiuse code 
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''if (prev_state == G.STATES.TAROT_PACK or prev_state == G.STATES.PLANET_PACK or'''
position = "before"
payload = '''
if G.slib_infiniuse then
    G.slib_infiniuse = nil
    card.ability.slib_no_sell_value = true
    card:set_cost()
elseif G.cry_muse then
	G.cry_muse = nil
	card.ability.slib_no_sell_value = true
	card:set_cost()
	delay(0.4)

	-- i make my own card eval status text :D

	card:juice_up()
	play_sound('generic1')
	attention_text({
		text = format_ui_value(card.ability.cry_multiuse),
		scale = 1.1,
		hold = 0.6,
		major = card,
		backdrop_colour = Spectrallib.get_text_colour(card),
		align = 'bm',
		offset = {x = 0, y = 0.2}
	})

	delay(0.8)
end
'''
match_indent = true
